// src/seeders/foodSeeder.js
// Seeds 35 realistic Pakistani foods with Faisalabad local prices
// Run: npm run seed

require('dotenv').config();
const mongoose = require('mongoose');
const FoodItem = require('../models/FoodItem');
const connectDB = require('../config/database');

const pakistaniFoods = [
  // ─── BREAKFAST ITEMS ─────────────────────────────────────
  {
    name: 'Aloo Paratha',
    calories: 320,
    protein: 7,
    carbs: 48,
    fat: 12,
    fiber: 3,
    price: 50,
    servingSize: '2 parathas (200g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: false,
    category: 'breakfast',
    mealType: ['breakfast'],
    allergens: ['gluten'],
    description: 'Classic Pakistani stuffed bread with spiced potato filling',
  },
  {
    name: 'Halwa Puri',
    calories: 450,
    protein: 8,
    carbs: 60,
    fat: 20,
    fiber: 2,
    price: 80,
    servingSize: '1 plate',
    is_diabetic_safe: false,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'breakfast',
    mealType: ['breakfast'],
    allergens: ['gluten'],
    description: 'Traditional Pakistani Sunday breakfast — fried bread with semolina dessert',
  },
  {
    name: 'Anda Paratha',
    calories: 370,
    protein: 14,
    carbs: 45,
    fat: 16,
    fiber: 2,
    price: 60,
    servingSize: '1 paratha with egg (220g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: false,
    category: 'breakfast',
    mealType: ['breakfast'],
    allergens: ['gluten', 'eggs'],
    description: 'Egg-stuffed whole wheat paratha',
  },
  {
    name: 'Doodh Pati Chai',
    calories: 120,
    protein: 4,
    carbs: 14,
    fat: 5,
    fiber: 0,
    price: 20,
    servingSize: '1 cup (240ml)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'beverage',
    mealType: ['breakfast', 'snack'],
    allergens: ['dairy'],
    description: 'Strong Pakistani milk tea',
  },
  {
    name: 'Namkeen Lassi',
    calories: 150,
    protein: 8,
    carbs: 12,
    fat: 7,
    fiber: 0,
    price: 40,
    servingSize: '1 glass (300ml)',
    is_diabetic_safe: true,
    is_hypertension_safe: false,
    is_cardiac_safe: true,
    category: 'beverage',
    mealType: ['breakfast', 'lunch'],
    allergens: ['dairy'],
    description: 'Salty yogurt-based drink, popular in Faisalabad',
  },
  {
    name: 'Meethi Lassi',
    calories: 220,
    protein: 8,
    carbs: 30,
    fat: 7,
    fiber: 0,
    price: 50,
    servingSize: '1 glass (300ml)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'beverage',
    mealType: ['breakfast'],
    allergens: ['dairy'],
    description: 'Sweet yogurt drink, Punjabi staple',
  },
  {
    name: 'Anday ka Nashta',
    calories: 250,
    protein: 18,
    carbs: 5,
    fat: 17,
    fiber: 1,
    price: 55,
    servingSize: '2 eggs with vegetables (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: false,
    category: 'breakfast',
    mealType: ['breakfast'],
    allergens: ['eggs'],
    description: 'Pakistani spiced scrambled eggs (bhurji) with tomatoes and onions',
  },
  {
    name: 'Khichdi',
    calories: 280,
    protein: 9,
    carbs: 52,
    fat: 5,
    fiber: 4,
    price: 45,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'breakfast',
    mealType: ['breakfast', 'dinner'],
    allergens: [],
    description: 'Comforting rice and lentil porridge — gentle on stomach',
  },

  // ─── BREAD ────────────────────────────────────────────────
  {
    name: 'Tandoori Roti',
    calories: 120,
    protein: 4,
    carbs: 24,
    fat: 1,
    fiber: 2,
    price: 15,
    servingSize: '1 roti (90g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'bread',
    mealType: ['lunch', 'dinner'],
    allergens: ['gluten'],
    description: 'Whole wheat flatbread baked in tandoor oven',
  },
  {
    name: 'Chapati (Phulka)',
    calories: 100,
    protein: 3,
    carbs: 20,
    fat: 1,
    fiber: 2,
    price: 10,
    servingSize: '1 chapati (70g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'bread',
    mealType: ['lunch', 'dinner'],
    allergens: ['gluten'],
    description: 'Thin whole wheat flatbread cooked on tawa',
  },
  {
    name: 'Naan',
    calories: 260,
    protein: 8,
    carbs: 48,
    fat: 4,
    fiber: 2,
    price: 25,
    servingSize: '1 naan (150g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'bread',
    mealType: ['lunch', 'dinner'],
    allergens: ['gluten', 'dairy'],
    description: 'Leavened tandoor-baked bread',
  },

  // ─── LENTILS ──────────────────────────────────────────────
  {
    name: 'Dal Masoor',
    calories: 230,
    protein: 15,
    carbs: 38,
    fat: 3,
    fiber: 8,
    price: 60,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'lentils',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Red lentil curry — most common Pakistani household dal',
  },
  {
    name: 'Dal Mash',
    calories: 210,
    protein: 14,
    carbs: 32,
    fat: 4,
    fiber: 7,
    price: 70,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'lentils',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'White lentil curry, Punjabi specialty',
  },
  {
    name: 'Dal Chana',
    calories: 250,
    protein: 13,
    carbs: 42,
    fat: 4,
    fiber: 9,
    price: 65,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'lentils',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Split chickpea lentil curry',
  },
  {
    name: 'Chana Masala',
    calories: 270,
    protein: 14,
    carbs: 40,
    fat: 6,
    fiber: 10,
    price: 80,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'lentils',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced chickpea curry — protein-rich Pakistani staple',
  },

  // ─── MEAT DISHES ─────────────────────────────────────────
  {
    name: 'Chicken Karahi',
    calories: 380,
    protein: 32,
    carbs: 8,
    fat: 24,
    fiber: 2,
    price: 200,
    servingSize: '1 serving (300g)',
    is_diabetic_safe: true,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'meat',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Classic Pakistani wok-cooked spicy chicken — Faisalabad style',
  },
  {
    name: 'Chicken Roast (Desi)',
    calories: 340,
    protein: 35,
    carbs: 5,
    fat: 20,
    fiber: 1,
    price: 180,
    servingSize: '2 pieces (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'meat',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced whole roasted chicken pieces',
  },
  {
    name: 'Beef Qeema',
    calories: 360,
    protein: 28,
    carbs: 6,
    fat: 25,
    fiber: 2,
    price: 160,
    servingSize: '1 bowl (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'meat',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Minced beef curry with peas — Pakistani household staple',
  },
  {
    name: 'Mutton Karahi',
    calories: 420,
    protein: 30,
    carbs: 6,
    fat: 30,
    fiber: 2,
    price: 280,
    servingSize: '1 serving (300g)',
    is_diabetic_safe: true,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'meat',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Rich mutton karahi — special occasion dish in Faisalabad',
  },
  {
    name: 'Chicken Tikka (Grilled)',
    calories: 290,
    protein: 38,
    carbs: 4,
    fat: 13,
    fiber: 1,
    price: 220,
    servingSize: '4 pieces (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'meat',
    mealType: ['lunch', 'dinner', 'snack'],
    allergens: ['dairy'],
    description: 'Yogurt-marinated grilled chicken — healthier option',
  },

  // ─── VEGETABLES & SABZI ──────────────────────────────────
  {
    name: 'Saag (Sarson)',
    calories: 180,
    protein: 8,
    carbs: 20,
    fat: 8,
    fiber: 6,
    price: 70,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'vegetable',
    mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Mustard greens cooked with butter — iconic Punjabi dish',
  },
  {
    name: 'Aloo Gosht',
    calories: 350,
    protein: 22,
    carbs: 25,
    fat: 18,
    fiber: 3,
    price: 150,
    servingSize: '1 bowl (300g)',
    is_diabetic_safe: false,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'meat',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Potato and mutton curry — beloved Pakistani comfort food',
  },
  {
    name: 'Bhindi Masala',
    calories: 150,
    protein: 4,
    carbs: 18,
    fat: 7,
    fiber: 5,
    price: 60,
    servingSize: '1 bowl (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'vegetable',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced okra stir-fry — diabetic-friendly vegetable',
  },
  {
    name: 'Karela (Bitter Gourd)',
    calories: 90,
    protein: 3,
    carbs: 12,
    fat: 3,
    fiber: 4,
    price: 50,
    servingSize: '1 bowl (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'vegetable',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Bitter gourd sabzi — excellent blood sugar control vegetable',
  },
  {
    name: 'Tinda Masala',
    calories: 120,
    protein: 3,
    carbs: 16,
    fat: 5,
    fiber: 3,
    price: 55,
    servingSize: '1 bowl (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'vegetable',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Indian round gourd cooked with spices',
  },
  {
    name: 'Palak Paneer',
    calories: 280,
    protein: 14,
    carbs: 18,
    fat: 17,
    fiber: 4,
    price: 120,
    servingSize: '1 bowl (250g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: false,
    category: 'vegetable',
    mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Spinach and cottage cheese curry',
  },

  // ─── RICE DISHES ─────────────────────────────────────────
  {
    name: 'Plain Boiled Rice',
    calories: 200,
    protein: 4,
    carbs: 44,
    fat: 0.5,
    fiber: 1,
    price: 30,
    servingSize: '1 cup cooked (180g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'rice',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Simple steamed white rice',
  },
  {
    name: 'Chicken Biryani',
    calories: 480,
    protein: 25,
    carbs: 65,
    fat: 14,
    fiber: 2,
    price: 180,
    servingSize: '1 plate (350g)',
    is_diabetic_safe: false,
    is_hypertension_safe: false,
    is_cardiac_safe: false,
    category: 'rice',
    mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Aromatic Pakistani chicken biryani — Faisalabad celebration food',
  },
  {
    name: 'Matar Pulao',
    calories: 320,
    protein: 9,
    carbs: 58,
    fat: 7,
    fiber: 4,
    price: 80,
    servingSize: '1 plate (300g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'rice',
    mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Fragrant peas and rice pilaf',
  },

  // ─── DAIRY ────────────────────────────────────────────────
  {
    name: 'Dahi (Plain Yogurt)',
    calories: 120,
    protein: 9,
    carbs: 10,
    fat: 4,
    fiber: 0,
    price: 40,
    servingSize: '1 cup (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'dairy',
    mealType: ['breakfast', 'lunch', 'dinner', 'snack'],
    allergens: ['dairy'],
    description: 'Plain Pakistani yogurt — probiotic rich',
  },
  {
    name: 'Raita',
    calories: 100,
    protein: 5,
    carbs: 10,
    fat: 4,
    fiber: 1,
    price: 30,
    servingSize: '1 cup (200g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'dairy',
    mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Yogurt with cucumber and mint',
  },

  // ─── SNACKS ───────────────────────────────────────────────
  {
    name: 'Samosa (Baked)',
    calories: 180,
    protein: 5,
    carbs: 25,
    fat: 7,
    fiber: 2,
    price: 30,
    servingSize: '2 pieces (120g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: false,
    category: 'snack',
    mealType: ['snack'],
    allergens: ['gluten'],
    description: 'Baked (not fried) spiced potato pastry — lighter option',
  },
  {
    name: 'Fruit Chaat',
    calories: 130,
    protein: 2,
    carbs: 30,
    fat: 1,
    fiber: 4,
    price: 60,
    servingSize: '1 bowl (200g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'snack',
    mealType: ['snack'],
    allergens: [],
    description: 'Mixed seasonal fruits with chaat masala — Pakistani street snack',
  },
  {
    name: 'Roasted Chana',
    calories: 170,
    protein: 10,
    carbs: 25,
    fat: 3,
    fiber: 7,
    price: 25,
    servingSize: '1 handful (50g)',
    is_diabetic_safe: true,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'snack',
    mealType: ['snack'],
    allergens: [],
    description: 'Dry roasted chickpeas — healthy high-protein snack',
  },
  {
    name: 'Seasonal Fruit (Mixed)',
    calories: 90,
    protein: 1,
    carbs: 22,
    fat: 0.5,
    fiber: 3,
    price: 50,
    servingSize: '1 serving (150g)',
    is_diabetic_safe: false,
    is_hypertension_safe: true,
    is_cardiac_safe: true,
    category: 'fruit',
    mealType: ['breakfast', 'snack'],
    allergens: [],
    description: 'Seasonal fruits: guava, mango, banana, papaya — local Faisalabad produce',
  },
];

const seedFoods = async () => {
  try {
    await connectDB();

    const existingCount = await FoodItem.countDocuments();
    if (existingCount > 0) {
      console.log(`\n⚠️  Database already has ${existingCount} food items.`);
      console.log('   Clearing and reseeding...\n');
      await FoodItem.deleteMany({});
    }

    const inserted = await FoodItem.insertMany(pakistaniFoods);
    console.log(`\n✅ Successfully seeded ${inserted.length} Pakistani food items!\n`);

    // Summary
    const categories = [...new Set(pakistaniFoods.map((f) => f.category))];
    console.log('📦 Categories seeded:', categories.join(', '));
    console.log('🩺 Diabetic-safe items:', pakistaniFoods.filter((f) => f.is_diabetic_safe).length);
    console.log('❤️  Cardiac-safe items:', pakistaniFoods.filter((f) => f.is_cardiac_safe).length);
    console.log('🩸 Hypertension-safe items:', pakistaniFoods.filter((f) => f.is_hypertension_safe).length);

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedFoods();
